### ISSUE TITLE
'System.Reflection.Emit.Lightweight' was not included in compilation, but was referenced in NetJSON.DynamicNetJSONSerializer.CreateDeserializerWithTextReader()

### ISSUE THREAD

**Issue by Nexxkinn** [rpgmaker/NetJSON#202]
My app works on debug mode, but throws this error if I compile it in release mode

```
 {System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property. ---> 
System.MissingMethodException: Method 'DynamicMethod..ctor(string, Type, Type[], Module, bool)' from assembly 'System.Reflection.Emit.Lightweight' was not included in compilation, but was referenced in NetJSON.DynamicNetJSONSerializer.CreateDeserializerWithTextReader(). There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
   at NetJSON.NetJSON.DynamicNetJSONSerializer`1..ctor()
   at NetJSON.NetJSON.NetJSONCachedSerializer`1.GetSerializer()
   at NetJSON.NetJSON.NetJSONCachedSerializer`1..cctor()
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext* pContext) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\ClassConstructorRunner.cs:line 92
   }
```
other computers from Microsoft also returns the same kind of error 
![image](https://user-images.githubusercontent.com/7548170/46713962-66116c00-cc83-11e8-802c-1ec6af41d9e0.png)

might be related : 
[Microsoft delisted System.Reflection.Emit.Lightweight for .NET Standard](https://github.com/mgravell/fast-member/issues/57)
[Should there be a .Net Standard 2.0 version of Reflection.Emit?](https://github.com/dotnet/corefx/issues/29365)

**Comment by rpgmaker** [comment]
Strange that this is happening. My .net standard test work fine. It should have failed even for the simple calls. I will look into it and get back to you .

Thanks for the find.

**Comment by rpgmaker** [comment]
I tested it again and it works fine with .net core 2.0+ without any issue. How are you consuming it?

![image](https://user-images.githubusercontent.com/557807/47059241-7c915900-d196-11e8-913d-8ac266482a20.png)

**Comment by Nexxkinn** [comment]
It does works in debug mode.
But it throws an error if  you build it on release mode, in my experience.

**Comment by rpgmaker** [comment]
Ok. i will try running in release mode. Thanks

**Comment by rpgmaker** [comment]
It also works in release mode.

![image](https://user-images.githubusercontent.com/557807/47059783-c418e480-d198-11e8-8998-fd35b4112221.png)

**Comment by rpgmaker** [comment]
Could you give me a code sample i can test with? 

Thanks,

**Comment by rpgmaker** [comment]
I will take a look at it and let you know. Thanks

**Comment by rpgmaker** [comment]
The changes was to remove Emitting of IL which i cannot remove since I need it in either dynamic assembly or dynamic method generation. Does DynamicMethod exists in UWP? if so then i can conditionally generate dynamic methods instead of seperate dynamic assembly.

**Comment by Nexxkinn** [comment]
>           The changes was to remove Emitting of IL which i cannot remove since I need it in either dynamic assembly or dynamic method generation. Does DynamicMethod exists in UWP? if so then i can conditionally generate dynamic methods instead of seperate dynamic assembly.

UWP ( and generally, any .Net Native-compiled apps ) doesn't support Reflection.Emit library, due to the nature of .Net Native apps to be run in AOT instead of JIT. I just realised this yesterday :/

Oh well, you can close this issue since it's .Net Native's problem instead.

**Comment by rpgmaker** [comment]
Thanks for verifying. 😀
