### ISSUE TITLE
Getting Exception when serializing a struct

### ISSUE THREAD

**Issue by peter-ringba** [rpgmaker/NetJSON#220]
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'NetJSONCachedSerializer`1' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NetJSON.NetJSON.GetMemberInfoValue(ILGenerator il, NetJSONMemberInfo parameter)
   at NetJSON.NetJSON.<>c__DisplayClass363_0.<GenerateGetClassOrDictFor>b__1(ILGenerator msil)
   at NetJSON.NetJSON.ILFixedWhile(ILGenerator il, Action`5 whileAction, Boolean needBreak, Action`1 returnAction, Action`2 beforeAction, Action`2 beginIndexIf, Action`2 endIndexIf)
   at NetJSON.NetJSON.GenerateGetClassOrDictFor(TypeBuilder typeBuilder, Type type)
   at NetJSON.NetJSON.WriteDeserializeMethodFor(TypeBuilder typeBuilder, Type type)
   at NetJSON.NetJSON.GenerateTypeBuilder(Type objType, ModuleBuilder module)
   at NetJSON.NetJSON.Generate(Type objType)
   at NetJSON.NetJSON.NetJSONCachedSerializer`1.GetSerializer()
   at NetJSON.NetJSON.NetJSONCachedSerializer`1..cctor()
```

```
public struct LogEntry
    {
        public string DateTimeString;
        public string ServerName;
        public long Epoch;
        public bool IsSuccess;
        public string LogId;
        public string RequestId;
        public string action;
        [NonSerialized]
        public long ticks;
        public double ms;
        public string failMessage;
        public SEVERITY severity;
        [NonSerialized]
        public string argsJson;


      //  public LogEntry() { }

        public LogEntry(string logId, string requestId, string action, long ticks, string failMessage, SEVERITY severity, string argsJson) : this()
        {
            LogId = logId;
            this.action = action;
            this.ticks = ticks;
            this.failMessage = failMessage;
            this.severity = severity;
            IsSuccess = false;
            RequestId = requestId;
            Epoch = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            DateTimeString = DateTime.UtcNow.ToString("o");
            ServerName = Environment.MachineName;
            this.argsJson = argsJson;
        }

    }

    public enum SEVERITY
    {
        ERROR
    }
```

**Comment by rpgmaker** [comment]
Thanks for the find. Could you give an example payload for the failure? Thanks

**Comment by rpgmaker** [comment]
Here is an example similar to your that already exists in the test suite which uses a struct and does not fail. Note, that it does not have a default constructor either and the test pass.

Something similar to the test i have below will be appreciated. Thanks

![image](https://user-images.githubusercontent.com/557807/58373742-2bea9700-7f01-11e9-9425-d36cd7031e10.png)


![image](https://user-images.githubusercontent.com/557807/58373746-3ad14980-7f01-11e9-9489-b3c18c31558c.png)

**Comment by rpgmaker** [comment]
Any example would be nice. Thanks

**Comment by rpgmaker** [comment]
Please reopen this issue if you are able to reproduce the issue again. Thanks
