### ISSUE TITLE
Enum in dictionary is not serilized

### ISSUE THREAD

**Issue by StefanBelo** [rpgmaker/NetJSON#59]
```C#
    public enum MyEnum
    {
        Start = 1,
        Stop
    }

    public class MyData
    {
        private Dictionary<string, object> parameters = new Dictionary<string, object>();

        public MyData()
        {
            SomeText = "Test";
            SomeEnum = MyEnum.Start;
        }

        public Dictionary<string, object> Parameters
        {
            get { return parameters; }
        }

        public string SomeText { get; set; }

        public MyEnum SomeEnum { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var myData = new MyData();

            var parameters = myData.Parameters;

            parameters.Add("textValue", "text");
            parameters.Add("intValue", 1);
            parameters.Add("doubleValue", 1.0);
            parameters.Add("enumValue", MyEnum.Start);

            NetJSON.NetJSON.UseEnumString = true;

            string json = NetJSON.NetJSON.Serialize<MyData>(myData);

            Debug.WriteLine(json);
        }
    }
```
Produces the following json:
```json
{"Parameters":{"textValue":"text","intValue":1,"doubleValue":1,"enumValue":""},"SomeText":"Test","SomeEnum":"Start"}
```

**Comment by rpgmaker** [comment]
It is not serialized because using object as a type for dictionary is limited to specific types. Making it work is as simple as adding enum to the list of type to look at during serialization and deserialization.

I will add it tonight or you can contribute the add if you want :)

Thanks,

**Comment by StefanBelo** [comment]
I have just downloaded your fixed version and run your test. TestEnumInDictionaryObject fails with this exception:

Test Name:	TestEnumInDictionaryObject
Test FullName:	NetJSON.Tests.SerializeTests.TestEnumInDictionaryObject
Test Source:	F:\Samples\NetJSON-master\NetJSON.Tests\SerializeTests.cs : line 29
Test Outcome:	Failed
Test Duration:	0:00:08,2046345

Result StackTrace:	
at System.Reflection.Emit.ILGenerator.Emit(OpCode opcode, MethodInfo meth)
   at NetJSON.NetJSON.<>c__DisplayClass220_0.<GenerateFastObjectToString>b__0(String _) in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 900
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NetJSON.NetJSON.GenerateFastObjectToString(TypeBuilder type) in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 778
   at NetJSON.NetJSON.WriteSerializeMethodFor(TypeBuilder typeBuilder, Type type, Boolean needQuote) in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 1629
   at NetJSON.NetJSON.WriteDictionary(TypeBuilder typeBuilder, Type type, ILGenerator il) in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 2020
   at NetJSON.NetJSON.WriteCollection(TypeBuilder typeBuilder, Type type, ILGenerator il) in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 1901
   at NetJSON.NetJSON.WriteSerializeFor(TypeBuilder typeBuilder, Type type, ILGenerator methodIL) in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 1886
   at NetJSON.NetJSON.WriteSerializeMethodFor(TypeBuilder typeBuilder, Type type, Boolean needQuote) in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 1846
   at NetJSON.NetJSON.GenerateTypeBuilder(Type objType, ModuleBuilder module) in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 969
   at NetJSON.NetJSON.Generate(Type objType) in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 950
   at NetJSON.NetJSON.NetJSONCachedSerializer`1..cctor() in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 155
 --- End of inner exception stack trace ---
    at NetJSON.NetJSON.GetSerializer[T]() in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 2403
   at NetJSON.NetJSON.Serialize[T](T value) in F:\Samples\NetJSON-master\NetJSON\NetJSON.cs:line 2479
   at NetJSON.Tests.SerializeTests.TestEnumInDictionaryObject() in F:\Samples\NetJSON-master\NetJSON.Tests\SerializeTests.cs:line 35
Result Message:	
Test method NetJSON.Tests.SerializeTests.TestEnumInDictionaryObject threw exception: 
System.TypeInitializationException: The type initializer for 'NetJSONCachedSerializer`1' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: meth

**Comment by rpgmaker** [comment]
Sorry about that. I forgot to add the method call for serializing char object for the dictionary[string, object] that i was testing. I have just checked it in here:

https://github.com/rpgmaker/NetJSON/commit/76a6d167983023d1bd1743f8a12e9d594bce24c3

**Comment by rpgmaker** [comment]
Can you please also try to deserialize the object too and see if that works for you? I did not test that yet when enum is included. But if you try to deserialize and it fail then you can go ahead reopen this issue then I can fix it if needs be.

**Comment by StefanBelo** [comment]
Well, we are almost there. In your test code you just added enum element to dictionary. In my use case the serialization is more similar to the code I provided. When I comment this line:

```C#
//parameters.Add("textValue", "text");
parameters.Add("intValue", 1);
parameters.Add("doubleValue", 1.0);
parameters.Add("enumValue", MyEnum.Start);
```
all works. So you have got a problem with string entry in the dictionary value, int, double and enum are correctly serialized. Deserialization works in my app.

Exception thrown when uncommenting the line:

```C#
parameters.Add("textValue", "text");
```

is:

Exception thrown: 'System.InvalidCastException' in MyDataClass

Unable to cast object of type 'System.String' to type 'System.Collections.IList'.

**Comment by rpgmaker** [comment]
So I broke string lol. It must be the changes I did for char that caused it. I will look into it.

**Comment by rpgmaker** [comment]
The issue was because of string was been translated as LIst because of it translate to IEnumerable[char]
