### ISSUE TITLE
TypeInitializationException with your home page example

### ISSUE THREAD

**Issue by rianjs** [rpgmaker/NetJSON#70]
This is a copy and paste of the example on your home page:

```
static void Main(string[] args)
{
    var obj = new {ID = 100, Name = "Test", Value = "Value"};
    var json = NetJSON.NetJSON.Serialize(obj);  //Explodes
}
```

Call stack:
```
at NetJSON.NetJSON.GetSerializer[T]()
at NetJSON.NetJSON.Serialize[T](T value)
at SerializationTester.Program.Main(String[] args) in D:\git\SerializationTester\SerializationTester\Program.cs:line 15
at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by rpgmaker** [comment]
Lol. This is not the example

var myObject = new SimpleObject(){ ID = 100, Name = "Test", Value = "Value" };

var json = NetJSON.Serialize(myObject);

var recreatedObject = NetJSON.Deserialize(json);

Anonymous type is not supported yet.https://github.com/rpgmaker/NetJSON/issues/10

**Comment by rpgmaker** [comment]
I will close this issue since it is same as the support for anonymous type

**Comment by rianjs** [comment]
Ah, quite right.
