### ISSUE TITLE
Failed to Serialize DateTime? Type

### ISSUE THREAD

**Issue by badboy22** [rpgmaker/NetJSON#87]
public class Dummy
    {
        public DateTime? DateTimeStamp;
        public int IntegerValue;
        public string StringValue;
        public List<Dummy> ListValue;
        public Dictionary<int, Dummy> DictionaryValue;
        public Dummy DummyObjValue;

        public Dummy(DateTime? dateTime=null)
        {
            ListValue = new List<Dummy>();
            DictionaryValue = new Dictionary<int, Dummy>();
            DateTimeStamp = dateTime ?? DateTime.UtcNow;
        }
    }

NetJSON.NetJSON.IncludeFields = true;
NetJSON.NetJSON.SkipDefaultValue = false;
NetJSON.NetJSON.Serialize(new Dummy());

InnerException: System.ArgumentNullException
       HResult=-2147467261
       Message=Value cannot be null.
Parameter name: con
       Source=mscorlib
       ParamName=con
       StackTrace:
            at System.Reflection.Emit.ILGenerator.Emit(OpCode opcode, ConstructorInfo con)
            at NetJSON.NetJSON.GenerateGetClassOrDictFor(TypeBuilder typeBuilder, Type type)
            at NetJSON.NetJSON.WriteDeserializeMethodFor(TypeBuilder typeBuilder, Type type)
            at NetJSON.NetJSON.GenerateTypeBuilder(Type objType, ModuleBuilder module)
            at NetJSON.NetJSON.Generate(Type objType)
            at NetJSON.NetJSON.NetJSONCachedSerializer`1..cctor()
       InnerException:

**Comment by rpgmaker** [comment]
The issue is that your class needs to have a default constructor. Serialization of nullable should work. Can you add default constructor and let me know the result?

Thanks,

**Comment by badboy22** [comment]
It's OK now.

Thanks.

**Comment by rpgmaker** [comment]
Thanks,
